name: Update Readme

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download awesome-list-generator
        run: |
          apt install wget -y
          wget https://github.com/iLLeniumStudios/awesome-list-generator/releases/download/v1.0.1/awesome-list-generator_1.0.1_Linux_x86_64.tar.gz
          tar -xvf awesome-list-generator_1.0.1_Linux_x86_64.tar.gz
          ./awesome-list-generator
